# Generated by Django 4.2.10 on 2024-07-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_quset_quest_type_quset_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quset',
            name='quset_id',
        ),
    ]
