# Generated by Django 4.2.10 on 2024-07-20 17:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_quset_quset_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=8)),
            ],
        ),
    ]
