# Generated by Django 4.2.10 on 2024-07-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_team_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_list',
            name='team',
            field=models.CharField(default='', max_length=25),
        ),
    ]
