# Generated by Django 4.2.10 on 2024-07-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_rounds_negative_mark_alter_rounds_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounds',
            name='pass_mark',
            field=models.IntegerField(default=0),
        ),
    ]
